### ISSUE TITLE
开源不完整(opensource not complete)

### ISSUE THREAD

**Issue by flyboyxiang** [Unit-X/srt_to_udp_server#1]
这个开源不完整，有些文件都没有

**Comment by andersc** [comment]
Sorry. I do not understand that language. Please use English or Swedish in the communication with us.

**Comment by flyboyxiang** [comment]
this opensource does not yet open completely,there are some files missing,such as SRTNet.h and SRTNet.cpp,so please upload  all the files the project included,many tbanks

**Comment by andersc** [comment]
That is not true. All files are included that are needed and the project runs and builds for all supported platforms:

Ubuntu
MacOS
Windows (x64)
Centos7

Here is the location for all auto builds ->
https://github.com/Unit-X/srt_to_udp_server/actions

And here is the output of one of them (Ubuntu) ->
https://github.com/Unit-X/srt_to_udp_server/runs/857309139?check_suite_focus=true

There are no missing files or anything failing. If you can't provide more detailed information that is relevant I need to close this issue since it does not make any sense.

**Comment by flyboyxiang** [comment]
i can not find SRTNet.h included in NetBrige.h,and not find SRTServer class,please tell me the location of them,thanks
